title: Nang Wei Lun's Portfolio
description: Personal website and portfolio of Nang Wei Lun
# author: Nang Wei Lun
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
# url: "https://nangweilun.github.io"
# You can add more configuration options here

# Social links for Minimal Mistakes
author:
  name: Nang Wei Lun
  links:
    - github: NangWeiLun
    - linkedin: wei-lun-nang-164728186

plugins:
  - jekyll-include-cache
